# SiCK-68 Shield Config
# Nice!Nano does not have hardware backlight support,
# so backlighting is disabled.

CONFIG_ZMK_KEYBOARD_NAME="SiCK-68"
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y

# Bluetooth settings
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Optional: enable if you want ZMK Studio support
# CONFIG_ZMK_STUDIO=y
